### PR TITLE
WAR-1865: Selenium: _make_browser() function got multiple values for keyword argument 'profile_dir'

### PR DESCRIPTION
**Pull request by safarheen**
Details are provided in the PR for the ticket: WAR-1813.
**Note:**
Adding geckodriver support  for firefox versions > 47 with selenium V3 in .travis.yml

### CODE REVIEW

**Comment by sanikakulkarni** [comment]
Changes are the same as [Py2 Pull Request](https://github.com/warriorframework/warriorframework/pull/425). This [comment](https://github.com/warriorframework/warriorframework/pull/425#discussion_r191690722)needs to be ported here. Current changes look good.

**Comment by sanikakulkarni** [comment]
python = 3.4.8, Selenium = 3.5.0, firefox = 60, chrome = 63: regression passes.
python = 3.4.8, Selenium = 2.53.0, firefox = 46, chrome = 63: regression fails with the following error:

```
-D- Opening browser 'firefox'                                                                [666/1846]│    browser_details["type"], **browser_optional_args)
-I- No value given for firefox binary, default firefox will be used for execution.                     │  File "/home/sanika/reviews/warriorframework/warrior/Framework/ClassUtils/WSelenium/browser_mgmt.py"
-I- Platform: Linux Firefox binary path: firefox                                                       │, line 68, in open_browser
-E- name 'basestring' is not defined                                                                   │    profile_dir, webdriver_remote_url, **kwargs)
Traceback (most recent call last):                                                                     │  File "/home/sanika/reviews/warriorframework/warrior/Framework/ClassUtils/WSelenium/browser_mgmt.py"
  File "/home/sanika/reviews/warriorframework_py3/warrior/Framework/ClassUtils/WSelenium/browser_mgmt.$│, line 518, in _make_browser
y", line 592, in _make_ff                                                                              │    profile_dir, **kwargs)
    firefox_profile=ff_profile, **optional_args)                                                       │  File "/home/sanika/reviews/warriorframework/warrior/Framework/ClassUtils/WSelenium/browser_mgmt.py"
  File "/home/sanika/python/lib/python3.4/site-packages/selenium/webdriver/firefox/webdriver.py", line │, line 617, in _make_chrome
62, in __init__                                                                                        │    webdriver_remote_url, desired_capabilities, **kwargs)
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.bin$│  File "/home/sanika/reviews/warriorframework/warrior/Framework/ClassUtils/WSelenium/browser_mgmt.py"
ry._get_firefox_start_cmd()                                                                            │, line 624, in _generic_make_browser
NameError: name 'basestring' is not defined                                                            │    browser = webdriver_type()
-I- Unable to create Firefox browser, one possible reason is becauseFirefox version >= 47.0.1 and Sele$│  File "/home/sanika/.local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line
ium version < 3.5In order to launch Firefox ver 47 and up, Selenium needs to be updated to >= 3.5and n$│ 62, in __init__
eds geckodriver > 0.16                                                                                 │    self.service.start()
-E- Unable to create browser for: firefox                                                              │  File "/home/sanika/.local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 1
-E- could not open browser on system=search_element, name=browser_3   
````

**Comment by sanikakulkarni** [comment]
Hi @safarheen,

Please debug the the issue mentioned in the previous comment and find out what is causing the failure. If you push new commits, please make sure to run selenium regression testing on the new code and attach the results to the JIRA ticket. If you are unsure as to how to run the complete selenium regression project, please either ask @venkat1077 or email me.

You can delete outdated selenium regression attachment from the JIRA ticket if the amount of attachments are getting out of hand.

Thanks,
Sanika

**Comment by safarheen** [comment]
Hi @sanikakulkarni ,

Looks like this is a known bug with 2.53.0 with py3. Could you please try it with 2.53.1 selenium version?
https://github.com/SeleniumHQ/selenium/issues/1820

Thanks,
Farheen

**Pull request merged**
