### PR TITLE
WAR-1968: Utility to move wapp static files to katana static during app install

### PR DESCRIPTION
**Pull request by bennfnc**
Hello,

Creating a pull request to handle installation of wapps inside a docker environment.
Features:
1. It successfully copies static files from wapps to katana/static and also removes them during uninstall. 
2. It also handles rollback of katana/static/wapp incase of unsuccessful uninstall. 
3. Refactor of installation code. (refer to ticket WAR-1968)
Please review it and merge to develop.

Thank you.

### CODE REVIEW

**Comment by sanikakulkarni** [comment]
REST Regression is failing. Travis has passed otherwise

**Comment by mavelyne** [comment]
This needs to use the Django setting variable STATIC_ROOT instead of assuming that our static files directory will always be katana/static. Also, properly setting STATIC_ROOT will allow us to use Django's collectstatic command instead of relying on custom scripts/commands.

Reference: https://docs.djangoproject.com/en/2.1/howto/static-files/#deployment

**Comment by mavelyne** [comment]
>           > This needs to use the Django setting variable STATIC_ROOT instead of assuming that our static files directory will always be katana/static. Also, properly setting STATIC_ROOT will allow us to use Django's collectstatic command instead of relying on custom scripts/commands.
> > Reference: https://docs.djangoproject.com/en/2.1/howto/static-files/#deployment
> 
> 
> Warrior uses multiple static directory locations. One inside katana/wapps and the other in katana/static (in the case where warrior is deployed as a container). How do you plan to handle multiple static directories?

That is exactly what setting a STATIC_ROOT is supposed to handle. The STATIC_ROOT directory is the destination for all static files collected by the Django collectstatic command.  The collectstatic command knows that /katana/static is a source of static files due to the STATICFILES_DIRS setting variable and that each app has its own static directory because they are Django apps that follow the Django structure for storing their own static files.

**Comment by sanikakulkarni** [comment]
Closing PR as functionality is not needed and PR is outdated

**Pull request closed without merging**
